export default {
	'border-radius': 'border-radius',
	'flexbox': ['flex', 'flexBasis', 'flexDirection', 'flexGrow', 'flexFlow', 'flexShrink', 'alignContent', 'alignItems', 'alignSelf', 'justifyContent', 'order'],
	'css-transitions': ['transition', 'transitionDelay', 'transitionDuration', 'transitionProperty', 'transitionTimingFunction'],
	'transforms3d': ['backfaceVisibility', 'perspective', 'perspectiveOrigin', 'transform', 'transformOrigin', 'transformStyle', 'transformOriginX', 'transformOriginY'],
	'css-animation': ['animation', 'animationDelay', 'animationDirection', 'animationFillMode', 'animationDuration', 'anmationIterationCount', 'animationName', 'animationPlayState', 'animationTimingFunction'],
	'appearance': 'appearance',
	'user-select': 'userSelect',
	'backdrop-filter': 'backdropFilter',
	'css3-boxsizing': 'boxSizing',
	'font-kerning' : 'fontKerning',
	'css-exclusions' : ['wrapFlow', 'wrapThrough', 'wrapMargin'],
	'css-snappoints' : ['scrollSnapType', 'scrollSnapPointsX', 'scrollSnapPointsY', 'scrollSnapDestination', 'scrollSnapCoordinate'],
	'text-emphasis' : ['textEmphasisPosition', 'textEmphasis', 'textEmphasisStyle', 'textEmphasisColor'],
	'css-text-align-last' : 'textAlignLast',
	'css-boxdecorationbreak' : 'boxDecorationBreak',
	'css-clip-path' : 'clipPath',
	'css-masks' : ['maskImage', 'maskMode', 'maskRepeat', 'maskPosition', 'maskClip', 'maskOrigin', 'maskSize', 'maskComposite', 'mask', 'maskBorderSource', 'maskBorderMode', 'maskBorderSlice', 'maskBorderWidth', 'maskBorderOutset', 'maskBorderRepeat', 'maskBorder', 'maskType'],
	'css-touch-action' : 'touchAction',
	'text-size-adjust' : 'textSizeAdjust',
	'text-decoration' : ['textDecorationStyle', 'textDecorationSkip', 'textDecorationLine', 'textDecorationColor'],
	'css-shapes' : ['shapeImageThreshold', 'shapeImageMargin', 'shapeImageOutside'],
	'css3-tabsize' : 'tabSize'
}