// flow-typed signature: 436768a2f1ede02fd150c054d74444f9
// flow-typed version: <<STUB>>/css-in-js-utils_v^1.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-in-js-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-in-js-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-in-js-utils/lib/__tests__/assignStyle-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/camelCaseProperty-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/cssifyDeclaration-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/cssifyObject-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/isPrefixedProperty-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/isPrefixedValue-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/isUnitlessProperty-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/normalizeProperty-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/resolveArrayValue-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/unprefixProperty-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/__tests__/unprefixValue-test' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/assignStyle' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/camelCaseProperty' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/cssifyDeclaration' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/cssifyObject' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/hyphenateProperty' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/index' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/isPrefixedProperty' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/isPrefixedValue' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/isUnitlessProperty' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/normalizeProperty' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/resolveArrayValue' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/unprefixProperty' {
  declare module.exports: any;
}

declare module 'css-in-js-utils/lib/unprefixValue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-in-js-utils/lib/__tests__/assignStyle-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/assignStyle-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/camelCaseProperty-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/camelCaseProperty-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/cssifyDeclaration-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/cssifyDeclaration-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/cssifyObject-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/cssifyObject-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/isPrefixedProperty-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/isPrefixedProperty-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/isPrefixedValue-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/isPrefixedValue-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/isUnitlessProperty-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/isUnitlessProperty-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/normalizeProperty-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/normalizeProperty-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/resolveArrayValue-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/resolveArrayValue-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/unprefixProperty-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/unprefixProperty-test'>;
}
declare module 'css-in-js-utils/lib/__tests__/unprefixValue-test.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/__tests__/unprefixValue-test'>;
}
declare module 'css-in-js-utils/lib/assignStyle.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/assignStyle'>;
}
declare module 'css-in-js-utils/lib/camelCaseProperty.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/camelCaseProperty'>;
}
declare module 'css-in-js-utils/lib/cssifyDeclaration.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/cssifyDeclaration'>;
}
declare module 'css-in-js-utils/lib/cssifyObject.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/cssifyObject'>;
}
declare module 'css-in-js-utils/lib/hyphenateProperty.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/hyphenateProperty'>;
}
declare module 'css-in-js-utils/lib/index.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/index'>;
}
declare module 'css-in-js-utils/lib/isPrefixedProperty.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/isPrefixedProperty'>;
}
declare module 'css-in-js-utils/lib/isPrefixedValue.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/isPrefixedValue'>;
}
declare module 'css-in-js-utils/lib/isUnitlessProperty.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/isUnitlessProperty'>;
}
declare module 'css-in-js-utils/lib/normalizeProperty.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/normalizeProperty'>;
}
declare module 'css-in-js-utils/lib/resolveArrayValue.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/resolveArrayValue'>;
}
declare module 'css-in-js-utils/lib/unprefixProperty.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/unprefixProperty'>;
}
declare module 'css-in-js-utils/lib/unprefixValue.js' {
  declare module.exports: $Exports<'css-in-js-utils/lib/unprefixValue'>;
}
