// flow-typed signature: 327919640746bcd117ba9d33af7d688b
// flow-typed version: <<STUB>>/gitbook_v^3.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook/bin/gitbook' {
  declare module.exports: any;
}

declare module 'gitbook/book' {
  declare module.exports: any;
}

declare module 'gitbook/lib/__tests__/gitbook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/__tests__/init' {
  declare module.exports: any;
}

declare module 'gitbook/lib/__tests__/module' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/decodeConfig' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/decodeGlobal' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/decodePage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/deprecate' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/encodeConfig' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/encodeGlobal' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/encodeNavigation' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/encodePage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/encodeProgress' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/encodeSummary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/api/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/browser' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/build' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/buildEbook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/getBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/getOutputFolder' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/init' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/install' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/options' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/parse' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/serve' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/server' {
  declare module.exports: any;
}

declare module 'gitbook/lib/cli/watch' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/__tests__/configSchema' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/configDefault' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/configFiles' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/configSchema' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/defaultBlocks' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/defaultFilters' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/defaultPlugins' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/extsAsciidoc' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/extsMarkdown' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/ignoreFiles' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/pluginAssetsFolder' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/pluginHooks' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/pluginPrefix' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/pluginResources' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/templatesFolder' {
  declare module.exports: any;
}

declare module 'gitbook/lib/constants/themePrefix' {
  declare module.exports: any;
}

declare module 'gitbook/lib/fs/__tests__/mock' {
  declare module.exports: any;
}

declare module 'gitbook/lib/fs/mock' {
  declare module.exports: any;
}

declare module 'gitbook/lib/fs/node' {
  declare module.exports: any;
}

declare module 'gitbook/lib/gitbook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/init' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeBookWithPage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeFile' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeGlossary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeGlossaryEntry' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeLanguages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeOutput' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeOutputWithPage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodePage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeReadme' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeSummary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeSummaryArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/encodeSummaryPart' {
  declare module.exports: any;
}

declare module 'gitbook/lib/json/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/config' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/glossary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/glossaryEntry' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/page' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/plugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/pluginDependency' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/summary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/summaryArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/summaryPart' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/templateBlock' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/__tests__/templateEngine' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/book' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/config' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/file' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/fs' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/glossary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/glossaryEntry' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/ignore' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/language' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/languages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/output' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/page' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/parser' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/plugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/pluginDependency' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/readme' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/summary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/summaryArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/summaryPart' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/templateBlock' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/templateEngine' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/templateOutput' {
  declare module.exports: any;
}

declare module 'gitbook/lib/models/templateShortcut' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/__tests__/addPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/__tests__/removePlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/__tests__/togglePlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/addPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/editPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/getPluginConfig' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/hasPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/isDefaultPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/removePlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/config/togglePlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/editArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/editPartTitle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/insertArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/insertPart' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/mergeAtLevel' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/moveArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/moveArticleAfter' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/__tests__/removeArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/editArticleRef' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/editArticleTitle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/editPartTitle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/indexArticleLevels' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/indexLevels' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/indexPartLevels' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/insertArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/insertPart' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/mergeAtLevel' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/moveArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/moveArticleAfter' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/removeArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/removePart' {
  declare module.exports: any;
}

declare module 'gitbook/lib/modifiers/summary/unshiftArticle' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/__tests__/createMock' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/__tests__/ebook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/__tests__/generateMock' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/__tests__/json' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/__tests__/website' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/callHook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/callPageHook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/createTemplateEngine' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/getConvertOptions' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/getCoverPath' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/getPDFTemplate' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/onFinish' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/onPage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/ebook/options' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/generateAssets' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/generateBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/generatePage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/generatePages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/getModifiers' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/helper/fileToOutput' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/helper/fileToURL' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/helper/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/helper/resolveFileToURL' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/helper/writeFile' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/json/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/json/onFinish' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/json/onPage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/json/options' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/addHeadingId' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/annotateText' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/fetchRemoteImages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/highlightCode' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/inlinePng' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/resolveLinks' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/svgToImg' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/__tests__/svgToPng' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/addHeadingId' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/annotateText' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/editHTMLElement' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/fetchRemoteImages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/highlightCode' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/inlineAssets' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/inlinePng' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/modifyHTML' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/resolveImages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/resolveLinks' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/svgToImg' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/modifiers/svgToPng' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/prepareAssets' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/preparePages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/preparePlugins' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/__tests__/i18n' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/copyPluginAssets' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/createTemplateEngine' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/listSearchPaths' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/onAsset' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/onFinish' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/onInit' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/onPage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/options' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/prepareI18n' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/prepareResources' {
  declare module.exports: any;
}

declare module 'gitbook/lib/output/website/state' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/listAssets' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/parseBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/parseGlossary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/parseIgnore' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/parsePageFromString' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/parseReadme' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/__tests__/parseSummary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/findParsableFile' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/listAssets' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/lookupStructureFile' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseConfig' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseGlossary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseIgnore' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseLanguages' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parsePage' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parsePageFromString' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parsePagesList' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseReadme' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseStructureFile' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/parseSummary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/validateConfig' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parse/walkSummary' {
  declare module.exports: any;
}

declare module 'gitbook/lib/parsers' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/findForBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/findInstalled' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/installPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/installPlugins' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/listDependencies' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/locateRootFolder' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/resolveVersion' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/sortDependencies' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/__tests__/validatePlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/findForBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/findInstalled' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/installPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/installPlugins' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/listBlocks' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/listDependencies' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/listDepsForBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/listFilters' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/listResources' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/loadForBook' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/loadPlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/locateRootFolder' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/resolveVersion' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/sortDependencies' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/toNames' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/validateConfig' {
  declare module.exports: any;
}

declare module 'gitbook/lib/plugins/validatePlugin' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/__tests__/conrefsLoader' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/__tests__/postRender' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/__tests__/replaceShortcuts' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/conrefsLoader' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/index' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/listShortcuts' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/postRender' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/render' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/renderFile' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/replaceShortcuts' {
  declare module.exports: any;
}

declare module 'gitbook/lib/templating/themesLoader' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/__tests__/git' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/__tests__/location' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/__tests__/path' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/command' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/error' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/genKey' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/git' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/images' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/location' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/mergeDefaults' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/path' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/promise' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/reducedObject' {
  declare module.exports: any;
}

declare module 'gitbook/lib/utils/timing' {
  declare module.exports: any;
}

declare module 'gitbook/testing/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook/bin/gitbook.js' {
  declare module.exports: $Exports<'gitbook/bin/gitbook'>;
}
declare module 'gitbook/book.js' {
  declare module.exports: $Exports<'gitbook/book'>;
}
declare module 'gitbook/lib/__tests__/gitbook.js' {
  declare module.exports: $Exports<'gitbook/lib/__tests__/gitbook'>;
}
declare module 'gitbook/lib/__tests__/init.js' {
  declare module.exports: $Exports<'gitbook/lib/__tests__/init'>;
}
declare module 'gitbook/lib/__tests__/module.js' {
  declare module.exports: $Exports<'gitbook/lib/__tests__/module'>;
}
declare module 'gitbook/lib/api/decodeConfig.js' {
  declare module.exports: $Exports<'gitbook/lib/api/decodeConfig'>;
}
declare module 'gitbook/lib/api/decodeGlobal.js' {
  declare module.exports: $Exports<'gitbook/lib/api/decodeGlobal'>;
}
declare module 'gitbook/lib/api/decodePage.js' {
  declare module.exports: $Exports<'gitbook/lib/api/decodePage'>;
}
declare module 'gitbook/lib/api/deprecate.js' {
  declare module.exports: $Exports<'gitbook/lib/api/deprecate'>;
}
declare module 'gitbook/lib/api/encodeConfig.js' {
  declare module.exports: $Exports<'gitbook/lib/api/encodeConfig'>;
}
declare module 'gitbook/lib/api/encodeGlobal.js' {
  declare module.exports: $Exports<'gitbook/lib/api/encodeGlobal'>;
}
declare module 'gitbook/lib/api/encodeNavigation.js' {
  declare module.exports: $Exports<'gitbook/lib/api/encodeNavigation'>;
}
declare module 'gitbook/lib/api/encodePage.js' {
  declare module.exports: $Exports<'gitbook/lib/api/encodePage'>;
}
declare module 'gitbook/lib/api/encodeProgress.js' {
  declare module.exports: $Exports<'gitbook/lib/api/encodeProgress'>;
}
declare module 'gitbook/lib/api/encodeSummary.js' {
  declare module.exports: $Exports<'gitbook/lib/api/encodeSummary'>;
}
declare module 'gitbook/lib/api/index.js' {
  declare module.exports: $Exports<'gitbook/lib/api/index'>;
}
declare module 'gitbook/lib/browser.js' {
  declare module.exports: $Exports<'gitbook/lib/browser'>;
}
declare module 'gitbook/lib/cli/build.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/build'>;
}
declare module 'gitbook/lib/cli/buildEbook.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/buildEbook'>;
}
declare module 'gitbook/lib/cli/getBook.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/getBook'>;
}
declare module 'gitbook/lib/cli/getOutputFolder.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/getOutputFolder'>;
}
declare module 'gitbook/lib/cli/index.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/index'>;
}
declare module 'gitbook/lib/cli/init.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/init'>;
}
declare module 'gitbook/lib/cli/install.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/install'>;
}
declare module 'gitbook/lib/cli/options.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/options'>;
}
declare module 'gitbook/lib/cli/parse.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/parse'>;
}
declare module 'gitbook/lib/cli/serve.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/serve'>;
}
declare module 'gitbook/lib/cli/server.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/server'>;
}
declare module 'gitbook/lib/cli/watch.js' {
  declare module.exports: $Exports<'gitbook/lib/cli/watch'>;
}
declare module 'gitbook/lib/constants/__tests__/configSchema.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/__tests__/configSchema'>;
}
declare module 'gitbook/lib/constants/configDefault.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/configDefault'>;
}
declare module 'gitbook/lib/constants/configFiles.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/configFiles'>;
}
declare module 'gitbook/lib/constants/configSchema.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/configSchema'>;
}
declare module 'gitbook/lib/constants/defaultBlocks.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/defaultBlocks'>;
}
declare module 'gitbook/lib/constants/defaultFilters.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/defaultFilters'>;
}
declare module 'gitbook/lib/constants/defaultPlugins.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/defaultPlugins'>;
}
declare module 'gitbook/lib/constants/extsAsciidoc.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/extsAsciidoc'>;
}
declare module 'gitbook/lib/constants/extsMarkdown.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/extsMarkdown'>;
}
declare module 'gitbook/lib/constants/ignoreFiles.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/ignoreFiles'>;
}
declare module 'gitbook/lib/constants/pluginAssetsFolder.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/pluginAssetsFolder'>;
}
declare module 'gitbook/lib/constants/pluginHooks.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/pluginHooks'>;
}
declare module 'gitbook/lib/constants/pluginPrefix.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/pluginPrefix'>;
}
declare module 'gitbook/lib/constants/pluginResources.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/pluginResources'>;
}
declare module 'gitbook/lib/constants/templatesFolder.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/templatesFolder'>;
}
declare module 'gitbook/lib/constants/themePrefix.js' {
  declare module.exports: $Exports<'gitbook/lib/constants/themePrefix'>;
}
declare module 'gitbook/lib/fs/__tests__/mock.js' {
  declare module.exports: $Exports<'gitbook/lib/fs/__tests__/mock'>;
}
declare module 'gitbook/lib/fs/mock.js' {
  declare module.exports: $Exports<'gitbook/lib/fs/mock'>;
}
declare module 'gitbook/lib/fs/node.js' {
  declare module.exports: $Exports<'gitbook/lib/fs/node'>;
}
declare module 'gitbook/lib/gitbook.js' {
  declare module.exports: $Exports<'gitbook/lib/gitbook'>;
}
declare module 'gitbook/lib/index.js' {
  declare module.exports: $Exports<'gitbook/lib/index'>;
}
declare module 'gitbook/lib/init.js' {
  declare module.exports: $Exports<'gitbook/lib/init'>;
}
declare module 'gitbook/lib/json/encodeBook.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeBook'>;
}
declare module 'gitbook/lib/json/encodeBookWithPage.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeBookWithPage'>;
}
declare module 'gitbook/lib/json/encodeFile.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeFile'>;
}
declare module 'gitbook/lib/json/encodeGlossary.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeGlossary'>;
}
declare module 'gitbook/lib/json/encodeGlossaryEntry.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeGlossaryEntry'>;
}
declare module 'gitbook/lib/json/encodeLanguages.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeLanguages'>;
}
declare module 'gitbook/lib/json/encodeOutput.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeOutput'>;
}
declare module 'gitbook/lib/json/encodeOutputWithPage.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeOutputWithPage'>;
}
declare module 'gitbook/lib/json/encodePage.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodePage'>;
}
declare module 'gitbook/lib/json/encodeReadme.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeReadme'>;
}
declare module 'gitbook/lib/json/encodeSummary.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeSummary'>;
}
declare module 'gitbook/lib/json/encodeSummaryArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeSummaryArticle'>;
}
declare module 'gitbook/lib/json/encodeSummaryPart.js' {
  declare module.exports: $Exports<'gitbook/lib/json/encodeSummaryPart'>;
}
declare module 'gitbook/lib/json/index.js' {
  declare module.exports: $Exports<'gitbook/lib/json/index'>;
}
declare module 'gitbook/lib/models/__tests__/config.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/config'>;
}
declare module 'gitbook/lib/models/__tests__/glossary.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/glossary'>;
}
declare module 'gitbook/lib/models/__tests__/glossaryEntry.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/glossaryEntry'>;
}
declare module 'gitbook/lib/models/__tests__/page.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/page'>;
}
declare module 'gitbook/lib/models/__tests__/plugin.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/plugin'>;
}
declare module 'gitbook/lib/models/__tests__/pluginDependency.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/pluginDependency'>;
}
declare module 'gitbook/lib/models/__tests__/summary.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/summary'>;
}
declare module 'gitbook/lib/models/__tests__/summaryArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/summaryArticle'>;
}
declare module 'gitbook/lib/models/__tests__/summaryPart.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/summaryPart'>;
}
declare module 'gitbook/lib/models/__tests__/templateBlock.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/templateBlock'>;
}
declare module 'gitbook/lib/models/__tests__/templateEngine.js' {
  declare module.exports: $Exports<'gitbook/lib/models/__tests__/templateEngine'>;
}
declare module 'gitbook/lib/models/book.js' {
  declare module.exports: $Exports<'gitbook/lib/models/book'>;
}
declare module 'gitbook/lib/models/config.js' {
  declare module.exports: $Exports<'gitbook/lib/models/config'>;
}
declare module 'gitbook/lib/models/file.js' {
  declare module.exports: $Exports<'gitbook/lib/models/file'>;
}
declare module 'gitbook/lib/models/fs.js' {
  declare module.exports: $Exports<'gitbook/lib/models/fs'>;
}
declare module 'gitbook/lib/models/glossary.js' {
  declare module.exports: $Exports<'gitbook/lib/models/glossary'>;
}
declare module 'gitbook/lib/models/glossaryEntry.js' {
  declare module.exports: $Exports<'gitbook/lib/models/glossaryEntry'>;
}
declare module 'gitbook/lib/models/ignore.js' {
  declare module.exports: $Exports<'gitbook/lib/models/ignore'>;
}
declare module 'gitbook/lib/models/language.js' {
  declare module.exports: $Exports<'gitbook/lib/models/language'>;
}
declare module 'gitbook/lib/models/languages.js' {
  declare module.exports: $Exports<'gitbook/lib/models/languages'>;
}
declare module 'gitbook/lib/models/output.js' {
  declare module.exports: $Exports<'gitbook/lib/models/output'>;
}
declare module 'gitbook/lib/models/page.js' {
  declare module.exports: $Exports<'gitbook/lib/models/page'>;
}
declare module 'gitbook/lib/models/parser.js' {
  declare module.exports: $Exports<'gitbook/lib/models/parser'>;
}
declare module 'gitbook/lib/models/plugin.js' {
  declare module.exports: $Exports<'gitbook/lib/models/plugin'>;
}
declare module 'gitbook/lib/models/pluginDependency.js' {
  declare module.exports: $Exports<'gitbook/lib/models/pluginDependency'>;
}
declare module 'gitbook/lib/models/readme.js' {
  declare module.exports: $Exports<'gitbook/lib/models/readme'>;
}
declare module 'gitbook/lib/models/summary.js' {
  declare module.exports: $Exports<'gitbook/lib/models/summary'>;
}
declare module 'gitbook/lib/models/summaryArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/models/summaryArticle'>;
}
declare module 'gitbook/lib/models/summaryPart.js' {
  declare module.exports: $Exports<'gitbook/lib/models/summaryPart'>;
}
declare module 'gitbook/lib/models/templateBlock.js' {
  declare module.exports: $Exports<'gitbook/lib/models/templateBlock'>;
}
declare module 'gitbook/lib/models/templateEngine.js' {
  declare module.exports: $Exports<'gitbook/lib/models/templateEngine'>;
}
declare module 'gitbook/lib/models/templateOutput.js' {
  declare module.exports: $Exports<'gitbook/lib/models/templateOutput'>;
}
declare module 'gitbook/lib/models/templateShortcut.js' {
  declare module.exports: $Exports<'gitbook/lib/models/templateShortcut'>;
}
declare module 'gitbook/lib/modifiers/config/__tests__/addPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/__tests__/addPlugin'>;
}
declare module 'gitbook/lib/modifiers/config/__tests__/removePlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/__tests__/removePlugin'>;
}
declare module 'gitbook/lib/modifiers/config/__tests__/togglePlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/__tests__/togglePlugin'>;
}
declare module 'gitbook/lib/modifiers/config/addPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/addPlugin'>;
}
declare module 'gitbook/lib/modifiers/config/editPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/editPlugin'>;
}
declare module 'gitbook/lib/modifiers/config/getPluginConfig.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/getPluginConfig'>;
}
declare module 'gitbook/lib/modifiers/config/hasPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/hasPlugin'>;
}
declare module 'gitbook/lib/modifiers/config/index.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/index'>;
}
declare module 'gitbook/lib/modifiers/config/isDefaultPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/isDefaultPlugin'>;
}
declare module 'gitbook/lib/modifiers/config/removePlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/removePlugin'>;
}
declare module 'gitbook/lib/modifiers/config/togglePlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/config/togglePlugin'>;
}
declare module 'gitbook/lib/modifiers/index.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/index'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/editArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/editArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/editPartTitle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/editPartTitle'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/insertArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/insertArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/insertPart.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/insertPart'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/mergeAtLevel.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/mergeAtLevel'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/moveArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/moveArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/moveArticleAfter.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/moveArticleAfter'>;
}
declare module 'gitbook/lib/modifiers/summary/__tests__/removeArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/__tests__/removeArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/editArticleRef.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/editArticleRef'>;
}
declare module 'gitbook/lib/modifiers/summary/editArticleTitle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/editArticleTitle'>;
}
declare module 'gitbook/lib/modifiers/summary/editPartTitle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/editPartTitle'>;
}
declare module 'gitbook/lib/modifiers/summary/index.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/index'>;
}
declare module 'gitbook/lib/modifiers/summary/indexArticleLevels.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/indexArticleLevels'>;
}
declare module 'gitbook/lib/modifiers/summary/indexLevels.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/indexLevels'>;
}
declare module 'gitbook/lib/modifiers/summary/indexPartLevels.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/indexPartLevels'>;
}
declare module 'gitbook/lib/modifiers/summary/insertArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/insertArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/insertPart.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/insertPart'>;
}
declare module 'gitbook/lib/modifiers/summary/mergeAtLevel.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/mergeAtLevel'>;
}
declare module 'gitbook/lib/modifiers/summary/moveArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/moveArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/moveArticleAfter.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/moveArticleAfter'>;
}
declare module 'gitbook/lib/modifiers/summary/removeArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/removeArticle'>;
}
declare module 'gitbook/lib/modifiers/summary/removePart.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/removePart'>;
}
declare module 'gitbook/lib/modifiers/summary/unshiftArticle.js' {
  declare module.exports: $Exports<'gitbook/lib/modifiers/summary/unshiftArticle'>;
}
declare module 'gitbook/lib/output/__tests__/createMock.js' {
  declare module.exports: $Exports<'gitbook/lib/output/__tests__/createMock'>;
}
declare module 'gitbook/lib/output/__tests__/ebook.js' {
  declare module.exports: $Exports<'gitbook/lib/output/__tests__/ebook'>;
}
declare module 'gitbook/lib/output/__tests__/generateMock.js' {
  declare module.exports: $Exports<'gitbook/lib/output/__tests__/generateMock'>;
}
declare module 'gitbook/lib/output/__tests__/json.js' {
  declare module.exports: $Exports<'gitbook/lib/output/__tests__/json'>;
}
declare module 'gitbook/lib/output/__tests__/website.js' {
  declare module.exports: $Exports<'gitbook/lib/output/__tests__/website'>;
}
declare module 'gitbook/lib/output/callHook.js' {
  declare module.exports: $Exports<'gitbook/lib/output/callHook'>;
}
declare module 'gitbook/lib/output/callPageHook.js' {
  declare module.exports: $Exports<'gitbook/lib/output/callPageHook'>;
}
declare module 'gitbook/lib/output/createTemplateEngine.js' {
  declare module.exports: $Exports<'gitbook/lib/output/createTemplateEngine'>;
}
declare module 'gitbook/lib/output/ebook/getConvertOptions.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/getConvertOptions'>;
}
declare module 'gitbook/lib/output/ebook/getCoverPath.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/getCoverPath'>;
}
declare module 'gitbook/lib/output/ebook/getPDFTemplate.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/getPDFTemplate'>;
}
declare module 'gitbook/lib/output/ebook/index.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/index'>;
}
declare module 'gitbook/lib/output/ebook/onFinish.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/onFinish'>;
}
declare module 'gitbook/lib/output/ebook/onPage.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/onPage'>;
}
declare module 'gitbook/lib/output/ebook/options.js' {
  declare module.exports: $Exports<'gitbook/lib/output/ebook/options'>;
}
declare module 'gitbook/lib/output/generateAssets.js' {
  declare module.exports: $Exports<'gitbook/lib/output/generateAssets'>;
}
declare module 'gitbook/lib/output/generateBook.js' {
  declare module.exports: $Exports<'gitbook/lib/output/generateBook'>;
}
declare module 'gitbook/lib/output/generatePage.js' {
  declare module.exports: $Exports<'gitbook/lib/output/generatePage'>;
}
declare module 'gitbook/lib/output/generatePages.js' {
  declare module.exports: $Exports<'gitbook/lib/output/generatePages'>;
}
declare module 'gitbook/lib/output/getModifiers.js' {
  declare module.exports: $Exports<'gitbook/lib/output/getModifiers'>;
}
declare module 'gitbook/lib/output/helper/fileToOutput.js' {
  declare module.exports: $Exports<'gitbook/lib/output/helper/fileToOutput'>;
}
declare module 'gitbook/lib/output/helper/fileToURL.js' {
  declare module.exports: $Exports<'gitbook/lib/output/helper/fileToURL'>;
}
declare module 'gitbook/lib/output/helper/index.js' {
  declare module.exports: $Exports<'gitbook/lib/output/helper/index'>;
}
declare module 'gitbook/lib/output/helper/resolveFileToURL.js' {
  declare module.exports: $Exports<'gitbook/lib/output/helper/resolveFileToURL'>;
}
declare module 'gitbook/lib/output/helper/writeFile.js' {
  declare module.exports: $Exports<'gitbook/lib/output/helper/writeFile'>;
}
declare module 'gitbook/lib/output/index.js' {
  declare module.exports: $Exports<'gitbook/lib/output/index'>;
}
declare module 'gitbook/lib/output/json/index.js' {
  declare module.exports: $Exports<'gitbook/lib/output/json/index'>;
}
declare module 'gitbook/lib/output/json/onFinish.js' {
  declare module.exports: $Exports<'gitbook/lib/output/json/onFinish'>;
}
declare module 'gitbook/lib/output/json/onPage.js' {
  declare module.exports: $Exports<'gitbook/lib/output/json/onPage'>;
}
declare module 'gitbook/lib/output/json/options.js' {
  declare module.exports: $Exports<'gitbook/lib/output/json/options'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/addHeadingId.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/addHeadingId'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/annotateText.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/annotateText'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/fetchRemoteImages.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/fetchRemoteImages'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/highlightCode.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/highlightCode'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/inlinePng.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/inlinePng'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/resolveLinks.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/resolveLinks'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/svgToImg.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/svgToImg'>;
}
declare module 'gitbook/lib/output/modifiers/__tests__/svgToPng.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/__tests__/svgToPng'>;
}
declare module 'gitbook/lib/output/modifiers/addHeadingId.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/addHeadingId'>;
}
declare module 'gitbook/lib/output/modifiers/annotateText.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/annotateText'>;
}
declare module 'gitbook/lib/output/modifiers/editHTMLElement.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/editHTMLElement'>;
}
declare module 'gitbook/lib/output/modifiers/fetchRemoteImages.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/fetchRemoteImages'>;
}
declare module 'gitbook/lib/output/modifiers/highlightCode.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/highlightCode'>;
}
declare module 'gitbook/lib/output/modifiers/index.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/index'>;
}
declare module 'gitbook/lib/output/modifiers/inlineAssets.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/inlineAssets'>;
}
declare module 'gitbook/lib/output/modifiers/inlinePng.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/inlinePng'>;
}
declare module 'gitbook/lib/output/modifiers/modifyHTML.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/modifyHTML'>;
}
declare module 'gitbook/lib/output/modifiers/resolveImages.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/resolveImages'>;
}
declare module 'gitbook/lib/output/modifiers/resolveLinks.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/resolveLinks'>;
}
declare module 'gitbook/lib/output/modifiers/svgToImg.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/svgToImg'>;
}
declare module 'gitbook/lib/output/modifiers/svgToPng.js' {
  declare module.exports: $Exports<'gitbook/lib/output/modifiers/svgToPng'>;
}
declare module 'gitbook/lib/output/prepareAssets.js' {
  declare module.exports: $Exports<'gitbook/lib/output/prepareAssets'>;
}
declare module 'gitbook/lib/output/preparePages.js' {
  declare module.exports: $Exports<'gitbook/lib/output/preparePages'>;
}
declare module 'gitbook/lib/output/preparePlugins.js' {
  declare module.exports: $Exports<'gitbook/lib/output/preparePlugins'>;
}
declare module 'gitbook/lib/output/website/__tests__/i18n.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/__tests__/i18n'>;
}
declare module 'gitbook/lib/output/website/copyPluginAssets.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/copyPluginAssets'>;
}
declare module 'gitbook/lib/output/website/createTemplateEngine.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/createTemplateEngine'>;
}
declare module 'gitbook/lib/output/website/index.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/index'>;
}
declare module 'gitbook/lib/output/website/listSearchPaths.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/listSearchPaths'>;
}
declare module 'gitbook/lib/output/website/onAsset.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/onAsset'>;
}
declare module 'gitbook/lib/output/website/onFinish.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/onFinish'>;
}
declare module 'gitbook/lib/output/website/onInit.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/onInit'>;
}
declare module 'gitbook/lib/output/website/onPage.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/onPage'>;
}
declare module 'gitbook/lib/output/website/options.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/options'>;
}
declare module 'gitbook/lib/output/website/prepareI18n.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/prepareI18n'>;
}
declare module 'gitbook/lib/output/website/prepareResources.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/prepareResources'>;
}
declare module 'gitbook/lib/output/website/state.js' {
  declare module.exports: $Exports<'gitbook/lib/output/website/state'>;
}
declare module 'gitbook/lib/parse/__tests__/listAssets.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/listAssets'>;
}
declare module 'gitbook/lib/parse/__tests__/parseBook.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/parseBook'>;
}
declare module 'gitbook/lib/parse/__tests__/parseGlossary.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/parseGlossary'>;
}
declare module 'gitbook/lib/parse/__tests__/parseIgnore.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/parseIgnore'>;
}
declare module 'gitbook/lib/parse/__tests__/parsePageFromString.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/parsePageFromString'>;
}
declare module 'gitbook/lib/parse/__tests__/parseReadme.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/parseReadme'>;
}
declare module 'gitbook/lib/parse/__tests__/parseSummary.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/__tests__/parseSummary'>;
}
declare module 'gitbook/lib/parse/findParsableFile.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/findParsableFile'>;
}
declare module 'gitbook/lib/parse/index.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/index'>;
}
declare module 'gitbook/lib/parse/listAssets.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/listAssets'>;
}
declare module 'gitbook/lib/parse/lookupStructureFile.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/lookupStructureFile'>;
}
declare module 'gitbook/lib/parse/parseBook.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseBook'>;
}
declare module 'gitbook/lib/parse/parseConfig.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseConfig'>;
}
declare module 'gitbook/lib/parse/parseGlossary.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseGlossary'>;
}
declare module 'gitbook/lib/parse/parseIgnore.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseIgnore'>;
}
declare module 'gitbook/lib/parse/parseLanguages.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseLanguages'>;
}
declare module 'gitbook/lib/parse/parsePage.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parsePage'>;
}
declare module 'gitbook/lib/parse/parsePageFromString.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parsePageFromString'>;
}
declare module 'gitbook/lib/parse/parsePagesList.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parsePagesList'>;
}
declare module 'gitbook/lib/parse/parseReadme.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseReadme'>;
}
declare module 'gitbook/lib/parse/parseStructureFile.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseStructureFile'>;
}
declare module 'gitbook/lib/parse/parseSummary.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/parseSummary'>;
}
declare module 'gitbook/lib/parse/validateConfig.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/validateConfig'>;
}
declare module 'gitbook/lib/parse/walkSummary.js' {
  declare module.exports: $Exports<'gitbook/lib/parse/walkSummary'>;
}
declare module 'gitbook/lib/parsers.js' {
  declare module.exports: $Exports<'gitbook/lib/parsers'>;
}
declare module 'gitbook/lib/plugins/__tests__/findForBook.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/findForBook'>;
}
declare module 'gitbook/lib/plugins/__tests__/findInstalled.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/findInstalled'>;
}
declare module 'gitbook/lib/plugins/__tests__/installPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/installPlugin'>;
}
declare module 'gitbook/lib/plugins/__tests__/installPlugins.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/installPlugins'>;
}
declare module 'gitbook/lib/plugins/__tests__/listDependencies.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/listDependencies'>;
}
declare module 'gitbook/lib/plugins/__tests__/locateRootFolder.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/locateRootFolder'>;
}
declare module 'gitbook/lib/plugins/__tests__/resolveVersion.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/resolveVersion'>;
}
declare module 'gitbook/lib/plugins/__tests__/sortDependencies.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/sortDependencies'>;
}
declare module 'gitbook/lib/plugins/__tests__/validatePlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/__tests__/validatePlugin'>;
}
declare module 'gitbook/lib/plugins/findForBook.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/findForBook'>;
}
declare module 'gitbook/lib/plugins/findInstalled.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/findInstalled'>;
}
declare module 'gitbook/lib/plugins/index.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/index'>;
}
declare module 'gitbook/lib/plugins/installPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/installPlugin'>;
}
declare module 'gitbook/lib/plugins/installPlugins.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/installPlugins'>;
}
declare module 'gitbook/lib/plugins/listBlocks.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/listBlocks'>;
}
declare module 'gitbook/lib/plugins/listDependencies.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/listDependencies'>;
}
declare module 'gitbook/lib/plugins/listDepsForBook.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/listDepsForBook'>;
}
declare module 'gitbook/lib/plugins/listFilters.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/listFilters'>;
}
declare module 'gitbook/lib/plugins/listResources.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/listResources'>;
}
declare module 'gitbook/lib/plugins/loadForBook.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/loadForBook'>;
}
declare module 'gitbook/lib/plugins/loadPlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/loadPlugin'>;
}
declare module 'gitbook/lib/plugins/locateRootFolder.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/locateRootFolder'>;
}
declare module 'gitbook/lib/plugins/resolveVersion.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/resolveVersion'>;
}
declare module 'gitbook/lib/plugins/sortDependencies.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/sortDependencies'>;
}
declare module 'gitbook/lib/plugins/toNames.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/toNames'>;
}
declare module 'gitbook/lib/plugins/validateConfig.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/validateConfig'>;
}
declare module 'gitbook/lib/plugins/validatePlugin.js' {
  declare module.exports: $Exports<'gitbook/lib/plugins/validatePlugin'>;
}
declare module 'gitbook/lib/templating/__tests__/conrefsLoader.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/__tests__/conrefsLoader'>;
}
declare module 'gitbook/lib/templating/__tests__/postRender.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/__tests__/postRender'>;
}
declare module 'gitbook/lib/templating/__tests__/replaceShortcuts.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/__tests__/replaceShortcuts'>;
}
declare module 'gitbook/lib/templating/conrefsLoader.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/conrefsLoader'>;
}
declare module 'gitbook/lib/templating/index.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/index'>;
}
declare module 'gitbook/lib/templating/listShortcuts.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/listShortcuts'>;
}
declare module 'gitbook/lib/templating/postRender.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/postRender'>;
}
declare module 'gitbook/lib/templating/render.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/render'>;
}
declare module 'gitbook/lib/templating/renderFile.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/renderFile'>;
}
declare module 'gitbook/lib/templating/replaceShortcuts.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/replaceShortcuts'>;
}
declare module 'gitbook/lib/templating/themesLoader.js' {
  declare module.exports: $Exports<'gitbook/lib/templating/themesLoader'>;
}
declare module 'gitbook/lib/utils/__tests__/git.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/__tests__/git'>;
}
declare module 'gitbook/lib/utils/__tests__/location.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/__tests__/location'>;
}
declare module 'gitbook/lib/utils/__tests__/path.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/__tests__/path'>;
}
declare module 'gitbook/lib/utils/command.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/command'>;
}
declare module 'gitbook/lib/utils/error.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/error'>;
}
declare module 'gitbook/lib/utils/fs.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/fs'>;
}
declare module 'gitbook/lib/utils/genKey.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/genKey'>;
}
declare module 'gitbook/lib/utils/git.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/git'>;
}
declare module 'gitbook/lib/utils/images.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/images'>;
}
declare module 'gitbook/lib/utils/location.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/location'>;
}
declare module 'gitbook/lib/utils/logger.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/logger'>;
}
declare module 'gitbook/lib/utils/mergeDefaults.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/mergeDefaults'>;
}
declare module 'gitbook/lib/utils/path.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/path'>;
}
declare module 'gitbook/lib/utils/promise.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/promise'>;
}
declare module 'gitbook/lib/utils/reducedObject.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/reducedObject'>;
}
declare module 'gitbook/lib/utils/timing.js' {
  declare module.exports: $Exports<'gitbook/lib/utils/timing'>;
}
declare module 'gitbook/testing/setup.js' {
  declare module.exports: $Exports<'gitbook/testing/setup'>;
}
